import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import {
  Trophy,
  BrainCircuit,
  TrendingUp,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  Home,
  Download,
} from "lucide-react";

import { getInterview } from "../services/interviewService";

const InterviewResult = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [interview, setInterview] = useState(null);

  useEffect(() => {
    fetchInterview();
  }, [id]);

  const fetchInterview = async () => {
    try {
      const res = await getInterview(id);
      setInterview(res.interview);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <div className="flex flex-col items-center gap-5">
          <Loader2 size={55} className="animate-spin text-cyan-400" />

          <h2 className="text-white text-2xl font-bold">
            Loading Interview Report...
          </h2>

          <p className="text-slate-400">
            DevSphere AI is preparing your results.
          </p>
        </div>
      </div>
    );
  }

  if (!interview) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <div className="text-center">
          <AlertTriangle size={65} className="mx-auto text-red-400" />

          <h2 className="mt-6 text-3xl font-bold text-white">
            Interview Result Not Found
          </h2>

          <button
            onClick={() => navigate("/dashboard")}
            className="mt-8 px-6 py-3 rounded-xl bg-cyan-500 text-black font-bold hover:bg-cyan-400 transition-all"
          >
            Go Dashboard
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 text-white">
      {/* Background Glow */}
      <div className="fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute -top-44 left-1/2 -translate-x-1/2 w-[750px] h-[750px] rounded-full bg-violet-500/10 blur-[170px]" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[500px] rounded-full bg-cyan-500/10 blur-[160px]" />
      </div>

      <div className="max-w-7xl mx-auto px-6 py-10">
        {/* Hero Header */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8">
          <div className="flex flex-col lg:flex-row justify-between items-center gap-8">
            <div>
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-300">
                <Trophy size={18} />
                Interview Completed
              </div>

              <h1 className="mt-5 text-5xl font-black">AI Interview Report</h1>

              <p className="text-slate-400 mt-3 text-lg">
                Here is your personalized interview performance generated by
                DevSphere AI.
              </p>
            </div>

            <div className="text-center">
              <div className="w-44 h-44 rounded-full border-[10px] border-cyan-500 flex items-center justify-center">
                <div>
                  <h2 className="text-6xl font-black text-cyan-400">
                    {interview.overallScore || 0}%
                  </h2>
                  <p className="text-slate-400 mt-2">Overall Score</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Score Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mt-10">
          {/* Technical */}
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 hover:border-cyan-500 transition-all">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-slate-400">Technical</p>
                <h2 className="text-4xl font-black mt-3 text-cyan-400">
                  {interview.technicalScore || 0}%
                </h2>
              </div>
              <BrainCircuit size={45} className="text-cyan-400" />
            </div>

            <div className="w-full bg-slate-800 h-3 rounded-full mt-6 overflow-hidden">
              <div
                className="h-full rounded-full bg-cyan-500 transition-all duration-700"
                style={{
                  width: `${interview.technicalScore || 0}%`,
                }}
              />
            </div>
          </div>

          {/* Communication */}
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 hover:border-violet-500 transition-all">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-slate-400">Communication</p>
                <h2 className="text-4xl font-black mt-3 text-violet-400">
                  {interview.communicationScore || 0}%
                </h2>
              </div>
              <TrendingUp size={45} className="text-violet-400" />
            </div>

            <div className="w-full bg-slate-800 h-3 rounded-full mt-6 overflow-hidden">
              <div
                className="h-full rounded-full bg-violet-500 transition-all duration-700"
                style={{
                  width: `${interview.communicationScore || 0}%`,
                }}
              />
            </div>
          </div>

          {/* Confidence */}
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 hover:border-emerald-500 transition-all">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-slate-400">Confidence</p>
                <h2 className="text-4xl font-black mt-3 text-emerald-400">
                  {interview.confidenceScore || 0}%
                </h2>
              </div>
              <CheckCircle2 size={45} className="text-emerald-400" />
            </div>

            <div className="w-full bg-slate-800 h-3 rounded-full mt-6 overflow-hidden">
              <div
                className="h-full rounded-full bg-emerald-500 transition-all duration-700"
                style={{
                  width: `${interview.confidenceScore || 0}%`,
                }}
              />
            </div>
          </div>

          {/* Overall Badge */}
          <div className="bg-gradient-to-br from-cyan-500 to-violet-600 rounded-3xl p-6">
            <p className="text-white/80">Overall Rating</p>
            <h2 className="text-5xl font-black mt-5">
              {interview.overallScore || 0}%
            </h2>
            <p className="mt-6 text-white/90">
              {interview.overallFeedback ||
                "Performance evaluation unavailable."}
            </p>
          </div>
        </div>

        {/* Feedback Section (Strengths & Weaknesses) */}
        <div className="grid lg:grid-cols-2 gap-8 mt-10">
          {/* Strengths */}
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8">
            <h2 className="text-2xl font-bold flex items-center gap-3 mb-6">
              <CheckCircle2 className="text-emerald-400" />
              Strengths
            </h2>

            {(interview.strengths || []).length > 0 ? (
              <div className="space-y-4">
                {interview.strengths.map((item, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-3 bg-slate-950 border border-slate-800 rounded-xl p-4"
                  >
                    <CheckCircle2
                      size={18}
                      className="text-emerald-400 shrink-0"
                    />
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-slate-400">No strengths available.</p>
            )}
          </div>

          {/* Areas to Improve */}
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8">
            <h2 className="text-2xl font-bold flex items-center gap-3 mb-6">
              <AlertTriangle className="text-amber-400" />
              Areas to Improve
            </h2>

            {interview.weaknesses?.length > 0 ? (
              <div className="space-y-4">
                {interview.weaknesses.map((item, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-3 bg-slate-950 border border-slate-800 rounded-xl p-4"
                  >
                    <AlertTriangle
                      size={18}
                      className="text-amber-400 shrink-0"
                    />
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-slate-400">
                Excellent! No major improvement areas.
              </p>
            )}
          </div>
        </div>

        {/* AI Detailed Feedback */}
        <div className="mt-10 bg-slate-900 border border-slate-800 rounded-3xl p-8">
          <h2 className="text-2xl font-bold flex items-center gap-3 mb-6">
            <BrainCircuit className="text-cyan-400" />
            DevSphere AI Feedback
          </h2>

          <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6">
            <p className="text-slate-300 leading-8 text-lg">
              {interview.overallFeedback || "No AI feedback available."}
            </p>
          </div>

          {interview.recommendations?.length > 0 && (
            <div className="mt-8">
              <h3 className="text-xl font-semibold mb-4">Recommendations</h3>

              <div className="space-y-3">
                {interview.recommendations.map((item, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-3 bg-slate-950 border border-slate-800 rounded-xl p-4"
                  >
                    <TrendingUp size={18} className="text-cyan-400 shrink-0" />
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="mt-10 flex flex-col md:flex-row gap-5 justify-center">
          <button
            onClick={() => navigate("/dashboard")}
            className="flex items-center justify-center gap-3 px-8 py-4 rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:scale-105 transition-all duration-300 font-semibold shadow-lg shadow-cyan-500/20"
          >
            <Home size={20} />
            Back to Dashboard
          </button>

          <button
            onClick={() => alert("PDF Report download will be added soon!")}
            className="flex items-center justify-center gap-3 px-8 py-4 rounded-2xl bg-slate-900 border border-slate-700 hover:border-cyan-500 hover:bg-slate-800 transition-all duration-300 font-semibold"
          >
            <Download size={20} />
            Download Report
          </button>
        </div>
      </div>
    </div>
  );
};

export default InterviewResult;
